name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./dist
          if-no-files-found: warn
  deploy-to-pages:
    runs-on: ubuntu-latest
    name: Deploy to Pages
    needs: build
    permissions:
      id-token: write
      contents: read
      pages: write
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1-beta
        with:
          artifact-name: github-pages
